spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cbank_db?serverTimezone=Asia/Seoul
    username: root
    password: hyhy
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: hyhy
      password: Gosan1997
#      uri: mongodb://localhost:27017/cbank
      database: cbank

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션
logging.level:
  org.hibernate.SQL: debug